# Generated by Django 5.1.5 on 2026-07-17 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(default='ERROR', max_length=20)),
                ('logger', models.CharField(max_length=200, null=True)),
                ('exc_type', models.CharField(max_length=200, null=True)),
                ('message', models.TextField()),
                ('traceback', models.TextField(null=True)),
                ('method', models.CharField(max_length=10, null=True)),
                ('path', models.CharField(max_length=500, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('actor', models.CharField(blank=True, max_length=150, null=True)),
                ('entity_type', models.CharField(max_length=100, null=True)),
                ('entity_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
