# Generated by Django 5.1.5 on 2026-07-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noteorm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteorm',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='noteorm',
            name='locked_by_session',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
